### PR TITLE
Feature/device fw update

### LINKED ISSUE #104: Introduction of endpoint for device firmware updates

### PR DESCRIPTION
**Pull request by roesekoSICKAG**

### CODE REVIEW

**Review by mrentsch65 — APPROVED** [review]

**Comment by wolfram-ladurner** [comment]
To locate the meta data file within the unzipped iolfw file, the filename of the iolfw file is needed (see 7.4.4.1 of the BLOB FW Upd. Spec.: "The file name [of the metadata file] shall be the same as for the entire archive except the extension that shall be 'xml'."). I would suggest to add an additional attribute (something like `iolfwFileName`) to the `deviceFirmwareUpdatePost` object.

**Comment by roesekoSICKAG** [comment]
> To locate the meta data file within the unzipped iolfw file, the filename of the iolfw file is needed (see 7.4.4.1 of the BLOB FW Upd. Spec.: "The file name [of the metadata file] shall be the same as for the entire archive except the extension that shall be 'xml'."). I would suggest to add an additional attribute (something like `iolfwFileName`) to the `deviceFirmwareUpdatePost` object.

Can it not be assumed to be the received file name?

**Comment by wolfram-ladurner** [comment]
> > To locate the meta data file within the unzipped iolfw file, the filename of the iolfw file is needed (see 7.4.4.1 of the BLOB FW Upd. Spec.: "The file name [of the metadata file] shall be the same as for the entire archive except the extension that shall be 'xml'."). I would suggest to add an additional attribute (something like `iolfwFileName`) to the `deviceFirmwareUpdatePost` object.
> 
> Can it not be assumed to be the received file name?

How is the file name received by the server?
The `deviceFirmwareUpdatePost` object only has the attribute `iolfwfile` (type/format string binary), which is the content of the iolfw file, or am I missing something here?

**Comment by roesekoSICKAG** [comment]
The filename is part of the header parameters because it uses the content type `multipart/form-data` which is defined in the RFC7578 (https://www.rfc-editor.org/rfc/rfc7578).
But you are right, maybe we should add a hint, how the filename is provided by giving a reference to the RFC.

**Review by OlafWestrik — APPROVED** [review]

**Pull request merged**
